sudo: required

env:
  - IMAGE_NAME="golang:staging"

services:
- docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y docker-engine=1.9.1-0~trusty

script:
- curl https://raw.githubusercontent.com/nkubala/runtimes-common/travis_test/structure_tests/ext_run.sh > ext_run.sh
- chmod +x ext_run.sh
- docker version
- docker build -t "$IMAGE_NAME" -q base/
- ./ext_run.sh -i "$IMAGE_NAME" -v --config test/test_config.json
