sudo: required

env:
  - IMAGE_NAME="golang:staging"

services:
- docker

env:
  global:
    - DOCKER_VERSION=1.9.1

before_install:
  - sudo apt-get -o Dpkg::Options="--force-confnew" install -y docker-engine=${DOCKER_VERSION}

script:
- curl https://raw.githubusercontent.com/nkubala/runtimes-common/travis_test/structure_tests/ext_run.sh > ext_run.sh
- chmod +x ext_run.sh
- docker version
- docker build -t "$IMAGE_NAME" -q base/
- ./ext_run.sh -i "$IMAGE_NAME" -v --config test/test_config.json
